### ISSUE TITLE
Morte del player

### ISSUE THREAD

**Issue by ElleEntertainment** [ElleEntertainment/VCOD#1]
dopo che il player muore, il TextManager si bugga, e segna:
" niente / valore_overkill " 

Dopo che si ritorna in combat torna tutto a posto

**Comment by Tiuz90** [comment]
Stasera sistemo, è dovuto al fatto che i dati del player non vengono mandati nell'update (per evitare troppi sendMessage visto che per ora non serve) ma solo quando viene attaccato

**Comment by Tiuz90** [comment]
Sistemato
